<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>BattleCheats</AssemblyName>
    <RootNamespace>BattleCheats</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GameDir>/home/abracadabra/.local/share/Steam/steamapps/common/Mount &amp; Blade II Bannerlord</GameDir>
    <GameBin>$(GameDir)/bin/Win64_Shipping_Client</GameBin>
    <ProtonPfx>/home/abracadabra/.local/share/Steam/steamapps/compatdata/261550/pfx/drive_c/ProgramData/Mount and Blade II Bannerlord</ProtonPfx>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.Core"><HintPath>$(GameBin)/TaleWorlds.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Library"><HintPath>$(GameBin)/TaleWorlds.Library.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.MountAndBlade"><HintPath>$(GameBin)/TaleWorlds.MountAndBlade.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.InputSystem"><HintPath>$(GameBin)/TaleWorlds.InputSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Localization"><HintPath>$(GameBin)/TaleWorlds.Localization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.CampaignSystem"><HintPath>$(GameBin)/TaleWorlds.CampaignSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.ObjectSystem"><HintPath>$(GameBin)/TaleWorlds.ObjectSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.DotNet"><HintPath>$(GameBin)/TaleWorlds.DotNet.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Engine"><HintPath>$(GameBin)/TaleWorlds.Engine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Collections"><HintPath>$(GameBin)/System.Collections.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>

  <Target Name="Deploy" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <ModFiles Include="$(TargetPath)" />
      <ModFiles Include="$(TargetDir)$(AssemblyName).pdb" Condition="Exists('$(TargetDir)$(AssemblyName).pdb')" />
    </ItemGroup>
    <Copy SourceFiles="@(ModFiles)" DestinationFolder="$(GameDir)/Modules/BattleCheats/bin/Win64_Shipping_Client/" />
    <Copy SourceFiles="SubModule.xml" DestinationFolder="$(GameDir)/Modules/BattleCheats/" />
  </Target>

</Project>
